apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containerization-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: containerization-test
    spec:
      containers:
        - name: containerization-test
          image: noprysk/containerization-test:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: containerization-test
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: containerization-test